BIN_PATH = /usr/bin

BMXR_BIN_FILE = bxr.rb
BMXR_BIN_NAME = bxr
MXR_BIN_FILE = mxr.rb
MXR_BIN_NAME = mxr

install:
	@cp $(BMXR_BIN_FILE) $(BIN_PATH)/$(BMXR_BIN_FILE)
	@cp $(MXR_BIN_FILE) $(BIN_PATH)/$(MXR_BIN_FILE)
	@rm -f $(BIN_PATH)/$(BMXR_BIN_NAME)
	@ln -s $(BIN_PATH)/$(BMXR_BIN_FILE) $(BIN_PATH)/$(BMXR_BIN_NAME)
	@rm -f $(BIN_PATH)/$(MXR_BIN_NAME)
	@ln -s $(BIN_PATH)/$(MXR_BIN_FILE) $(BIN_PATH)/$(MXR_BIN_NAME)
